### ISSUE TITLE
Ergonomic development workflow

### ISSUE THREAD

**Issue by thanethomson** [informalsystems/quartz#102]
As a Quartz app developer (applies to our team too, since we're building MTCS as a Quartz-based app), I want to create my base application using a single command and develop and test locally with a really quick feedback loop.

Since we know that a Quartz-based app consists of at least 3 different parts (front-end, chain and enclave), we make the following assumptions about each part:
* Front-end: the developer will run this on their own, since every front-end framework will have its own development process.
* Chain: by default we provide a way to run a standalone `neutrond` validator  in a Docker container. The user can customize/replace this if they want.
* Enclave: leveraging https://github.com/informalsystems/cycles-quartz/pull/82 to build and run our enclave inside a Docker container without needing an SGX-capable CPU.

Ideally, spinning up the chain + enclave should be as easy as `docker-compose up`. And then when you want to make changes, you'd run `docker-compose down && docker-compose up`.

```[tasklist]
### Tasks
- [ ] https://github.com/informalsystems/cycles-quartz/pull/82
- [ ] https://github.com/informalsystems/cycles-quartz/issues/61
- [ ] https://github.com/informalsystems/cycles-quartz/pull/110
- [ ] https://github.com/informalsystems/cycles-quartz/issues/112
```
