### ISSUE TITLE
Release v0.1 follow-up 

### ISSUE THREAD

**Issue by hu55a1n1** [informalsystems/quartz#249]
## TODOs
- [ ] Either add missing README.mds or remove `readme` field for every crate
- [ ] Dry run each crate to ensure no publishing errors. (run `cargo publish --dry-run` for each Crate`)
- [ ] Make repo public
- [ ] Publish and tag release (see #190)
- [ ] Update the transfers app to point to the published versions.
- [ ] Update `template_path` in CLI `quartz init` to point to git address when open-sourced
