### ISSUE TITLE
Protocol proposals

### ISSUE THREAD

**Issue by hu55a1n1** [informalsystems/quartz#33]
## Summary
We need to document what we envision TEE on-chain registration/RA, key-managers, etc. to look like preferably in the form of protocol proposals (RFCs?).

```[tasklist]
### Tasks
- [ ] Proposal for on-chain TEE registration/revocation.
- [ ] Proposal for on-chain TEE remote-attestation verification.
- [ ] Proposal for key-managers.
```
