### ISSUE TITLE
Quartz tooling for deployment

### ISSUE THREAD

**Issue by ebuchman** [informalsystems/quartz#61]
Thinking about the quartz dev experience, especially around deployment. Here's a short writeup on some things we discussed today with Shoaib and Thane.

With Dan's recent refactor of the quartz core enclave code, the app-specific logic now lives on its own in its own directory. 

So a quartz app moving forward should have the following directory structure:

```
/
.. contracts/
.. enclave/
.. frontend/

```

And it can be in its own repo. For now our two quartz apps are living in the cycles-quartz repo, but in the future they could be in their own repos.

This is basically what we have now, but we also have this additional set of janky bash scripts for deployment. Instead of having those scripts, we discussed creating a `quartz` tool that would run on the enclave's host machine with the following commands:

```
$ quartz init                   # create base quartz app directory from template
$ quartz build                  # build the contract and enclave binaries
$ quartz start                  # gramine config (including light client), sign, start the enclave binary
$ quartz deploy $BINARY         # deploy the wasm binary to the chain and call instantiate
$ quartz handshake $CONTRACT    # run the handshake between contract and enclave (could be combined with `deploy`)
$ quartz listen $CONTRACT       # listen for events and run the enclave handler, and expose public query server for users
```

Maybe `listen` should be called `run` but I'll leave it as listen for now.

We could also add a `quartz init` to run on the dev machine to initialize the repo with template contract and enclave code to help devs get started. But the tool is mostly about easing deployment and getting rid of the scripts.

The scripts are currently a mix of bash code (init.sh, handshake.sh, etc.) and rust code called from bash (tm-prover).

The `quartz` tool should be written in rust (obviously), but for ease of getting started we can have it just include parts of the bash scripts as strings in its binary that it can execute directly. Might not be possible for everything but can probably help us get started quickly. Over time we can move more and more of the functionaltiy from the bash scripts into rust proper.

One thing to note is that some deployment stuff will actually be application specific, and we want this `quartz` tool to be general purpose. The way we achieve this is by putting more burden on the `enclave` code to handle things.

For instance, `quartz deploy` includes a call to the enclave's Instantiate method. This may need to return application specific data.

More significantly is `quartz listen`, which starts the main daemon to listen for blockchain events and trigger execution on the enclave. This may need to be customized in arbitrary ways. But in general it should be possible to boil this down to having the host query for data over the network and run functions on the enclave. Thus `quartz listen` will get everything it needs from the enclave. The enclave can tell it what events to subscribe to. And when events are triggered, it can ask the enclave what queries to make, before returning those results to the enclave for processing. 

Note this does mean it can trigger some execution on the enclave that is not strictly controlled by the blockchain (ie. asking it what queries to make of the blockchain in the first place). In principle this should be ok, just something to note.

Additionally, we can have `quartz listen` expose a public query server so users can query enclave data. Making queries possible requires a lot more work (specifically adding ORAM), but it makes sense for the single `quartz listen` command to handle all requests for execution from the enclave whether from users or the blockchain itself.

So, a short summary of some flows for `quartz listen`:

        - ask the enclave what to subscribe to on the blockchain
        - listen for those events from the blockchain
                - when event comes in, ask the enclave what to query
                - return results to enclave
                - submit result from enclave back to chain
        - listen on public address for queries from users 
                - have some basic spam prevention
                - forward queries to enclave
                - enclave requests host to query data from blockchain
                - host forwards blockchain data to enclave
                - enclave responds with response for user
                - host returns response to user

```[tasklist]
### Tasks
- [ ] https://github.com/informalsystems/cycles-quartz/pull/105
- [ ] https://github.com/informalsystems/cycles-quartz/issues/113
- [ ] https://github.com/informalsystems/cycles-quartz/issues/114
- [ ] https://github.com/informalsystems/cycles-quartz/issues/115
- [ ] https://github.com/informalsystems/cycles-quartz/issues/116
- [ ] https://github.com/informalsystems/cycles-quartz/issues/117
- [ ] https://github.com/informalsystems/cycles-quartz/issues/118
- [ ] https://github.com/informalsystems/cycles-quartz/issues/120
```
