### ISSUE TITLE
Use DCAP as the default RA type

### ISSUE THREAD

**Issue by hu55a1n1** [informalsystems/quartz#70]
## Acceptance Criteria
- [x] Impl DCAP attestor
- [x] Impl DCAP verifier
- [x] Make DCAP RA default (includes changes to enclaves, gramine manifests, cw packages, etc.)
- [x] Test that it all works end-to-end

Depends on #100 
```[tasklist]
### Tasks
- [x] Remove proxy, listen goes inside enclave, and also change EPID from listen, to DPAC in enclave (see #100 too)
- [ ] https://github.com/informalsystems/cycles-quartz/issues/175
- [ ] https://github.com/informalsystems/cycles-quartz/issues/218
- [ ] https://github.com/informalsystems/cycles-quartz/issues/219
```
